Only pass through changed files
carloscuesta/starterkit pull request #48
Opened 2016-10-24 21:08 UTC by SergiSMJ

Files are passed through the whole pipe chain on every run by default. By
using gulp-changed only changed files will be passed through. This can
speed up consecutive runs considerably.

Optimize build file process #47

2016-10-25 07:29 UTC, carloscuesta requested changes
Split the declarations into one ver per require assignment, and use tabs as indenting. This will fix the linter issues and the CI will pass 👍

2016-10-25 07:34 UTC, carloscuesta commented
Thanks for sending a pull request @SergiSMJ, please take a look at the requested changes

2016-10-26 09:48 UTC, SergiSMJ commented
Oh my fault, I will fix that!

2016-10-26 14:02 UTC, carloscuesta commented
@SergiSMJ Pull changes before commiting again, some pullrequests have been merged against the master branch. 👍

2017-01-06 22:28 UTC, closed without merging